// Claude'un düzeltmeleri ("sonuçlarıma bak"). Geçmiş sekmesinde görünür.
window.FEEDBACK = [
  { zeit: '2026-09-30 17:12', id: 'n0445:wort', antwort: 'Geld', richtig: 'das Geld', urteil: 'falsch', text: 'İsim hep artikeliyle: das Geld.' },
  { zeit: '2026-09-30 17:15', id: 'v448:satz', antwort: 'Ich schicke ihnen das Buch.', richtig: 'Ich schenke Ihnen ein Buch.', urteil: 'falsch', text: 'schenken = hediye etmek (schicken = göndermek). Siz (resmi) → Ihnen, büyük I. "bir kitap" → ein Buch.' },
  { zeit: '2026-09-30 17:15', id: 'v652:frm', antwort: 'sind gewohnt', richtig: 'hat gewohnt', urteil: 'falsch', text: 'wohnen Perfekt\'te haben alır: er hat gewohnt (yer değiştirme yok).' },
  { zeit: '2026-09-30 17:16', id: 'v448:frm', antwort: 'hat geschickt', richtig: 'hat geschenkt', urteil: 'falsch', text: 'schenken → geschenkt; geschickt schicken\'in Partizip\'i.' },
  { zeit: '2026-10-02 11:00', id: 'p01:1', antwort: 'Schmerz', richtig: 'Schmerzen', urteil: 'fast', text: '"starke ___ im Hals": çoğul, die Schmerzen.' },
  { zeit: '2026-10-02 11:00', id: 'p01:5', antwort: 'untersuchen', richtig: 'untersucht', urteil: 'fast', text: 'Özne "die Ärztin" (o): untersucht.' },
  { zeit: '2026-10-02 11:01', id: 'p01:6', antwort: 'schreibt', richtig: 'verschreibt', urteil: 'falsch', text: 'İlaç yazmak = verschreiben (ver- ön eki ayrılmaz): Sie verschreibt mir ein Medikament.' },
  { zeit: '2026-10-02 11:01', id: 'p01:8', antwort: 'Apoteke', richtig: 'Apotheke', urteil: 'fast', text: 'Yazım: Apo-th-eke (th).' },
  { zeit: '2026-10-02 11:02', id: 'v243:satz', antwort: 'gefahrt', richtig: 'gefahren', urteil: 'falsch', text: 'fahren düzensiz: Partizip gefahren (sind gefahren).' },
  { zeit: '2026-10-02 11:04', id: 'n1121:wort', antwort: 'Stadt', richtig: 'die Stadt', urteil: 'falsch', text: 'İsim hep artikeliyle: die Stadt (Pl. die Städte).' },
  { zeit: '2026-10-02 11:05', id: 'n1290:wort', antwort: 'Urlaub', richtig: 'der Urlaub', urteil: 'falsch', text: 'Artikeliyle: der Urlaub.' },
  { zeit: '2026-10-02 11:06', id: 'v243:frm', antwort: 'du fahrst', richtig: 'du fährst', urteil: 'fast', text: 'fahren: du fährst, er fährt (a → ä).' },
  { zeit: '2026-10-02 11:11', id: 'n0841:wort', antwort: 'der Name', richtig: 'der Vorname', urteil: 'fast', text: 'Soru belirsizdi ("ad"); ön ad = der Vorname. Türkçesi düzeltildi.' },
  { zeit: '2026-10-02 11:11', id: 'n0840:wort', antwort: 'der Nachname', richtig: 'der Familienname', urteil: 'richtig', text: 'Nachname da doğru; artık kabul ediliyor.' },
  { zeit: '2026-10-02 11:12', id: 'v240:abr', antwort: 'etwas sagen', richtig: 'erzählen von', urteil: 'falsch', text: 'anlatmak = erzählen (von + Dat): Er erzählt von seiner Reise.' },
  { zeit: '2026-10-02 11:13', id: 'v002:satz', antwort: 'Wir fahren ab', richtig: 'Fahren wir ab?', urteil: 'falsch', text: 'Evet/hayır sorusu: fiil başa gelir.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'Ich wurde den Frühesten Zug nehmen', richtig: 'Ich wollte den frühesten Zug nehmen.', urteil: 'falsch', text: 'Yazma: niyet = wollte (wurde = oldu). Sıfat küçük harf.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'das Traditionales Essen ausprobieren', richtig: 'das traditionelle Essen probieren', urteil: 'falsch', text: 'Yazma: traditionell; das + sıfat → -e.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'Ich hoffe, alles gut ist.', richtig: 'Ich hoffe, alles ist gut. / …, dass alles gut ist.', urteil: 'fast', text: 'Yazma: dass yoksa fiil 2. sırada.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'eine Dinge', richtig: 'eine Sache', urteil: 'falsch', text: 'Yazma: das Ding (ein Ding); daha doğal: eine Sache.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'Kannst du das denken?', richtig: 'Kannst du dir das vorstellen?', urteil: 'falsch', text: 'Yazma: hayal etmek = sich (D) etwas vorstellen.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'trozt des schlehtes Wetters', richtig: 'trotz des schlechten Wetters', urteil: 'falsch', text: 'Yazma: trotz + Genitiv; des + sıfat → -en.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'Wenn ich in Hamburg war', richtig: 'Als ich in Hamburg war', urteil: 'falsch', text: 'Yazma: geçmişte tek olay → als (wenn: her seferinde / gelecekte).' },
  { zeit: '2026-10-02 11:38', id: 'v642:satz', antwort: 'Wenden Sie nicht an das Amt?', richtig: 'Wenden Sie sich nicht ans Amt?', urteil: 'falsch', text: 'Dönüşlü zamir eksik: sich wenden an.' },
  { zeit: '2026-10-02 11:40', id: 'v646:frm', antwort: 'hat widersprecht', richtig: 'hat widersprochen', urteil: 'falsch', text: 'sprechen → gesprochen; widersprechen → widersprochen (ge- yok).' },
  { zeit: '2026-10-02 12:09', id: 'v646:satz', antwort: 'Da muss ich Ihren widersprechen.', richtig: 'Da muss ich Ihnen widersprechen.', urteil: 'falsch', text: 'widersprechen + Dativ: Ihnen (Ihren = iyelik).' },
  { zeit: '2026-10-02 12:09', id: 'v626:satz', antwort: 'Ich vorschlage, dass …', richtig: 'Ich schlage vor, dass wir eine Pause machen.', urteil: 'falsch', text: 'Ayrılan fiil: ich schlage … vor.' },
  { zeit: '2026-10-02 12:10', id: 'v626:frm', antwort: 'er schläge vor', richtig: 'er schlug vor', urteil: 'falsch', text: 'Präteritum: schlagen → schlug.' },
  { zeit: '2026-10-02 12:10', id: 'n0682:wort', antwort: 'der Kritik', richtig: 'die Kritik', urteil: 'falsch', text: '-ik ile bitenler çoğunlukla die.' },
  { zeit: '2026-10-02 11:40', id: 'n1240:wort', antwort: 'die Training', richtig: 'das Training', urteil: 'falsch', text: 'İngilizceden gelen -ing isimleri genelde das.' },
  { zeit: '2026-10-02 12:33', id: 'v620:abr', antwort: 'versichte an', richtig: 'verzichten auf (+ Akk)', urteil: 'falsch', text: 'verzichten (z-ch) auf: Ich verzichte auf den Kaffee.' },
  { zeit: '2026-10-02 12:34', id: 'v111:abr', antwort: 'sich berühmen um', richtig: 'sich bemühen um (+ Akk)', urteil: 'falsch', text: 'be-müh-en (Mühe = zahmet).' },
  { zeit: '2026-10-03', id: 'v673:satz', antwort: 'Ich zweifele an ihren nicht.', richtig: 'Ich zweifle nicht daran, dass Sie recht haben.', urteil: 'falsch', text: 'Arkasından yan cümle gelince an → daran, dass …; resmî siz = Sie.' },
  { zeit: '2026-10-03', id: 'v620:abr', antwort: 'vershreieb', richtig: 'verzichten auf (+ Akk)', urteil: 'falsch', text: 'vazgeçmek = verzichten auf; verschreiben = reçete yazmak.' },
  { zeit: '2026-10-03', id: 'v111:abr', antwort: 'sich bewerben um', richtig: 'sich bemühen um', urteil: 'falsch', text: 'bewerben um = başvurmak, bemühen um = çabalamak.' },
  { zeit: '2026-10-03', id: 'n0682:nsatz', antwort: 'viele gute Kritik', richtig: 'sehr gute Kritiken', urteil: 'fast', text: 'die Kritik → çoğul die Kritiken.' },
  { zeit: '2026-10-03', id: 'v673:frm', antwort: 'hat geweifelnt', richtig: 'hat gezweifelt', urteil: 'falsch', text: 'Düzenli: ge- + kök + -t.' },
  { zeit: '2026-10-03', id: 'v643:stamm', antwort: 'wurde, ist gewurden', richtig: 'wurde, ist geworden', urteil: 'falsch', text: 'Perfekt: geworden (o).' },
  { zeit: '2026-10-03', id: 'v527:stamm', antwort: 'traf, ist getraffen', richtig: 'traf, hat getroffen', urteil: 'falsch', text: 'Hareket değil → haben; Partizip getroffen.' },
  { zeit: '2026-10-03', id: 'v157:stamm', antwort: 'brach, hat gebrachen', richtig: 'brachte, hat gebracht', urteil: 'falsch', text: 'bringen karışık fiil: brachte, gebracht (brechen ile karıştı).' },
  { zeit: '2026-10-03', id: 'v148:stamm', antwort: 'bleib, ist geblieben', richtig: 'blieb, ist geblieben', urteil: 'fast', text: 'ei → ie: blieb.' },
  { zeit: '2026-10-03', id: 'p02:1', antwort: 'Angebote', richtig: 'Anzeige', urteil: 'falsch', text: 'eine interessante ___ → tekil dişil: die Anzeige (ilan).' },
  { zeit: '2026-10-03', id: 'p02:8', antwort: 'verschreibe', richtig: 'unterschreibe', urteil: 'falsch', text: 'unterschreiben = imzalamak, verschreiben = reçete yazmak.' },
];
