// Claude'un düzeltmeleri ("sonuçlarıma bak"). Geçmiş sekmesinde görünür.
window.FEEDBACK = [
  { zeit: '2026-09-30 17:12', id: 'n0445:wort', antwort: 'Geld', richtig: 'das Geld', urteil: 'falsch', text: 'İsim hep artikeliyle: das Geld.' },
  { zeit: '2026-09-30 17:15', id: 'v448:satz', antwort: 'Ich schicke ihnen das Buch.', richtig: 'Ich schenke Ihnen ein Buch.', urteil: 'falsch', text: 'schenken = hediye etmek (schicken = göndermek). Siz (resmi) → Ihnen, büyük I. "bir kitap" → ein Buch.' },
  { zeit: '2026-09-30 17:15', id: 'v652:frm', antwort: 'sind gewohnt', richtig: 'hat gewohnt', urteil: 'falsch', text: 'wohnen Perfekt\'te haben alır: er hat gewohnt (yer değiştirme yok).' },
  { zeit: '2026-09-30 17:16', id: 'v448:frm', antwort: 'hat geschickt', richtig: 'hat geschenkt', urteil: 'falsch', text: 'schenken → geschenkt; geschickt schicken\'in Partizip\'i.' },
  { zeit: '2026-10-02 11:00', id: 'p01:1', antwort: 'Schmerz', richtig: 'Schmerzen', urteil: 'fast', text: '"starke ___ im Hals": çoğul, die Schmerzen.' },
  { zeit: '2026-10-02 11:00', id: 'p01:5', antwort: 'untersuchen', richtig: 'untersucht', urteil: 'fast', text: 'Özne "die Ärztin" (o): untersucht.' },
  { zeit: '2026-10-02 11:01', id: 'p01:6', antwort: 'schreibt', richtig: 'verschreibt', urteil: 'falsch', text: 'İlaç yazmak = verschreiben (ver- ön eki ayrılmaz): Sie verschreibt mir ein Medikament.' },
  { zeit: '2026-10-02 11:01', id: 'p01:8', antwort: 'Apoteke', richtig: 'Apotheke', urteil: 'fast', text: 'Yazım: Apo-th-eke (th).' },
  { zeit: '2026-10-02 11:02', id: 'v243:satz', antwort: 'gefahrt', richtig: 'gefahren', urteil: 'falsch', text: 'fahren düzensiz: Partizip gefahren (sind gefahren).' },
  { zeit: '2026-10-02 11:04', id: 'n1121:wort', antwort: 'Stadt', richtig: 'die Stadt', urteil: 'falsch', text: 'İsim hep artikeliyle: die Stadt (Pl. die Städte).' },
  { zeit: '2026-10-02 11:05', id: 'n1290:wort', antwort: 'Urlaub', richtig: 'der Urlaub', urteil: 'falsch', text: 'Artikeliyle: der Urlaub.' },
  { zeit: '2026-10-02 11:06', id: 'v243:frm', antwort: 'du fahrst', richtig: 'du fährst', urteil: 'fast', text: 'fahren: du fährst, er fährt (a → ä).' },
  { zeit: '2026-10-02 11:11', id: 'n0841:wort', antwort: 'der Name', richtig: 'der Vorname', urteil: 'fast', text: 'Soru belirsizdi ("ad"); ön ad = der Vorname. Türkçesi düzeltildi.' },
  { zeit: '2026-10-02 11:11', id: 'n0840:wort', antwort: 'der Nachname', richtig: 'der Familienname', urteil: 'richtig', text: 'Nachname da doğru; artık kabul ediliyor.' },
  { zeit: '2026-10-02 11:12', id: 'v240:abr', antwort: 'etwas sagen', richtig: 'erzählen von', urteil: 'falsch', text: 'anlatmak = erzählen (von + Dat): Er erzählt von seiner Reise.' },
  { zeit: '2026-10-02 11:13', id: 'v002:satz', antwort: 'Wir fahren ab', richtig: 'Fahren wir ab?', urteil: 'falsch', text: 'Evet/hayır sorusu: fiil başa gelir.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'Ich wurde den Frühesten Zug nehmen', richtig: 'Ich wollte den frühesten Zug nehmen.', urteil: 'falsch', text: 'Yazma: niyet = wollte (wurde = oldu). Sıfat küçük harf.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'das Traditionales Essen ausprobieren', richtig: 'das traditionelle Essen probieren', urteil: 'falsch', text: 'Yazma: traditionell; das + sıfat → -e.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'Ich hoffe, alles gut ist.', richtig: 'Ich hoffe, alles ist gut. / …, dass alles gut ist.', urteil: 'fast', text: 'Yazma: dass yoksa fiil 2. sırada.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'eine Dinge', richtig: 'eine Sache', urteil: 'falsch', text: 'Yazma: das Ding (ein Ding); daha doğal: eine Sache.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'Kannst du das denken?', richtig: 'Kannst du dir das vorstellen?', urteil: 'falsch', text: 'Yazma: hayal etmek = sich (D) etwas vorstellen.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'trozt des schlehtes Wetters', richtig: 'trotz des schlechten Wetters', urteil: 'falsch', text: 'Yazma: trotz + Genitiv; des + sıfat → -en.' },
  { zeit: '2026-10-02 12:31', id: 'a01', antwort: 'Wenn ich in Hamburg war', richtig: 'Als ich in Hamburg war', urteil: 'falsch', text: 'Yazma: geçmişte tek olay → als (wenn: her seferinde / gelecekte).' },
  { zeit: '2026-10-02 11:38', id: 'v642:satz', antwort: 'Wenden Sie nicht an das Amt?', richtig: 'Wenden Sie sich nicht ans Amt?', urteil: 'falsch', text: 'Dönüşlü zamir eksik: sich wenden an.' },
  { zeit: '2026-10-02 11:40', id: 'v646:frm', antwort: 'hat widersprecht', richtig: 'hat widersprochen', urteil: 'falsch', text: 'sprechen → gesprochen; widersprechen → widersprochen (ge- yok).' },
  { zeit: '2026-10-02 12:09', id: 'v646:satz', antwort: 'Da muss ich Ihren widersprechen.', richtig: 'Da muss ich Ihnen widersprechen.', urteil: 'falsch', text: 'widersprechen + Dativ: Ihnen (Ihren = iyelik).' },
  { zeit: '2026-10-02 12:09', id: 'v626:satz', antwort: 'Ich vorschlage, dass …', richtig: 'Ich schlage vor, dass wir eine Pause machen.', urteil: 'falsch', text: 'Ayrılan fiil: ich schlage … vor.' },
  { zeit: '2026-10-02 12:10', id: 'v626:frm', antwort: 'er schläge vor', richtig: 'er schlug vor', urteil: 'falsch', text: 'Präteritum: schlagen → schlug.' },
  { zeit: '2026-10-02 12:10', id: 'n0682:wort', antwort: 'der Kritik', richtig: 'die Kritik', urteil: 'falsch', text: '-ik ile bitenler çoğunlukla die.' },
  { zeit: '2026-10-02 11:40', id: 'n1240:wort', antwort: 'die Training', richtig: 'das Training', urteil: 'falsch', text: 'İngilizceden gelen -ing isimleri genelde das.' },
  { zeit: '2026-10-02 12:33', id: 'v620:abr', antwort: 'versichte an', richtig: 'verzichten auf (+ Akk)', urteil: 'falsch', text: 'verzichten (z-ch) auf: Ich verzichte auf den Kaffee.' },
  { zeit: '2026-10-02 12:34', id: 'v111:abr', antwort: 'sich berühmen um', richtig: 'sich bemühen um (+ Akk)', urteil: 'falsch', text: 'be-müh-en (Mühe = zahmet).' },
  { zeit: '2026-10-03', id: 'v673:satz', antwort: 'Ich zweifele an ihren nicht.', richtig: 'Ich zweifle nicht daran, dass Sie recht haben.', urteil: 'falsch', text: 'Arkasından yan cümle gelince an → daran, dass …; resmî siz = Sie.' },
  { zeit: '2026-10-03', id: 'v620:abr', antwort: 'vershreieb', richtig: 'verzichten auf (+ Akk)', urteil: 'falsch', text: 'vazgeçmek = verzichten auf; verschreiben = reçete yazmak.' },
  { zeit: '2026-10-03', id: 'v111:abr', antwort: 'sich bewerben um', richtig: 'sich bemühen um', urteil: 'falsch', text: 'bewerben um = başvurmak, bemühen um = çabalamak.' },
  { zeit: '2026-10-03', id: 'n0682:nsatz', antwort: 'viele gute Kritik', richtig: 'sehr gute Kritiken', urteil: 'fast', text: 'die Kritik → çoğul die Kritiken.' },
  { zeit: '2026-10-03', id: 'v673:frm', antwort: 'hat geweifelnt', richtig: 'hat gezweifelt', urteil: 'falsch', text: 'Düzenli: ge- + kök + -t.' },
  { zeit: '2026-10-03', id: 'v643:stamm', antwort: 'wurde, ist gewurden', richtig: 'wurde, ist geworden', urteil: 'falsch', text: 'Perfekt: geworden (o).' },
  { zeit: '2026-10-03', id: 'v527:stamm', antwort: 'traf, ist getraffen', richtig: 'traf, hat getroffen', urteil: 'falsch', text: 'Hareket değil → haben; Partizip getroffen.' },
  { zeit: '2026-10-03', id: 'v157:stamm', antwort: 'brach, hat gebrachen', richtig: 'brachte, hat gebracht', urteil: 'falsch', text: 'bringen karışık fiil: brachte, gebracht (brechen ile karıştı).' },
  { zeit: '2026-10-03', id: 'v148:stamm', antwort: 'bleib, ist geblieben', richtig: 'blieb, ist geblieben', urteil: 'fast', text: 'ei → ie: blieb.' },
  { zeit: '2026-10-03', id: 'p02:1', antwort: 'Angebote', richtig: 'Anzeige', urteil: 'falsch', text: 'eine interessante ___ → tekil dişil: die Anzeige (ilan).' },
  { zeit: '2026-10-03', id: 'p02:8', antwort: 'verschreibe', richtig: 'unterschreibe', urteil: 'falsch', text: 'unterschreiben = imzalamak, verschreiben = reçete yazmak.' },
  { zeit: '2026-10-03', id: 'n0682:nsatz', antwort: '—', richtig: 'Es gibt viel Kritik an der Politik der Regierung.', urteil: 'falsch', text: 'Kritik an + Dat: eleştiri … -e. die Regierung = hükümet.' },
  { zeit: '2026-10-03', id: 'n0660:nsatz', antwort: '—', richtig: 'Die Kosten für die Reise bekomme ich von der Firma.', urteil: 'falsch', text: 'die Kosten hep çoğul; für die Reise = yolculuk için.' },
  { zeit: '2026-10-03', id: 'v620:abr', antwort: 'verzcihten auf a', richtig: 'verzichten auf (+ Akk)', urteil: 'fast', text: 'Yazım: ver-zich-ten (ch önce, sonra t).' },
  { zeit: '2026-10-03', id: 'v673:satz', antwort: 'zweifel', richtig: 'zweifle', urteil: 'falsch', text: '-eln fiillerinde ich formunda e düşer: ich zweifle, ich sammle.' },
  { zeit: '2026-10-03', id: 'v157:stamm', antwort: 'bringt, bracht, hat gebracht', richtig: 'bringt, brachte, hat gebracht', urteil: 'fast', text: 'Karışık fiil: Präteritum -te alır: brachte.' },
  { zeit: '2026-10-03', id: 'n0433:wort', antwort: '—', richtig: 'die Geduld', urteil: 'falsch', text: 'sabır = die Geduld (Bitte haben Sie etwas Geduld).' },
  { zeit: '2026-10-03', id: 'v125:satz', antwort: 'Beschweren sie sich nicht bei ihrem Vermiter?', richtig: 'Können sie sich nicht bei ihrem Vermieter beschweren?', urteil: 'falsch', text: 'können istendi: modal başa, beschweren sona. Yazım: Vermieter (ie).' },
  { zeit: '2026-10-03', id: 'n0432:wort', antwort: '—', richtig: 'das Gedicht', urteil: 'falsch', text: 'şiir = das Gedicht.' },
  { zeit: '2026-10-03', id: 'v125:satz', antwort: '—', richtig: 'Haben wir uns beim Chef beschwert?', urteil: 'falsch', text: 'Perfekt: haben + uns + beschwert (be- ile ge- yok). bei dem → beim.' },
  { zeit: '2026-10-04', id: 'n0869:wort', antwort: 'das Operation', richtig: 'die Operation', urteil: 'fast', text: '-ion ile biten isimler die: die Operation, die Information, die Situation.' },
  { zeit: '2026-10-04', id: 'w0171:prod', antwort: 'folgende', richtig: 'folgend', urteil: 'fast', text: 'Sözlük biçimi folgend; folgende çekimli hâli (die folgende Seite). Aslında doğru sayılabilir.' },
  { zeit: '2026-10-04', id: 'p03:0', antwort: 'anmeldung', richtig: 'Anmeldung', urteil: 'fast', text: 'İsimler büyük harfle: die Anmeldung.' },
  { zeit: '2026-10-04', id: 'p03:1', antwort: 'Ämt', richtig: 'Amt', urteil: 'fast', text: 'Tekil das Amt; umlaut yalnız çoğulda: die Ämter.' },
  { zeit: '2026-10-04', id: 'p03:7', antwort: 'wohnung', richtig: 'Wohnsitz', urteil: 'falsch', text: 'der Wohnsitz = ikamet adresi (resmî). die Wohnung = daire.' },
  { zeit: '2026-10-04', id: 'p03:8', antwort: 'Behörde', richtig: 'Behörden', urteil: 'fast', text: 'Metinde çoğul: die Behörden.' },
  { zeit: '2026-10-04', id: 'v646:satz', antwort: 'wiedersagen', richtig: 'widersprechen', urteil: 'falsch', text: 'widersprechen + Dat (Ihnen) = itiraz etmek; wider (karşı) tek i: wider-sprechen.' },
  { zeit: '2026-10-04', id: 'v626:satz', antwort: 'vorgeschlagt', richtig: 'vorgeschlagen', urteil: 'falsch', text: 'schlagen güçlü fiil: geschlagen → vorgeschlagen.' },
  { zeit: '2026-10-04', id: 'n0037:wort', antwort: 'anmeldung', richtig: 'die Anmeldung', urteil: 'fast', text: 'Artikel + büyük harf: die Anmeldung (-ung → die).' },
  { zeit: '2026-10-04', id: 'v620:satz', antwort: 'verzihte', richtig: 'verzichte', urteil: 'fast', text: 'Yazım: verzichte (ch).' },
  { zeit: '2026-10-04', id: 'v629:abr', antwort: 'sich vorsehen?', richtig: 'sich (D) vorstellen', urteil: 'falsch', text: 'sich etwas vorstellen = hayal etmek (Ich kann mir das nicht vorstellen). sich vorsehen = dikkat etmek.' },
  { zeit: '2026-10-04', id: 'v642:abr', antwort: '—', richtig: 'sich wenden an (+ Akk)', urteil: 'falsch', text: 'Bitte wenden Sie sich an die Rezeption = resepsiyona başvurun.' },
  { zeit: '2026-10-04', id: 'v672:abr', antwort: '—', richtig: 'zustimmen (+ Dat)', urteil: 'falsch', text: 'Ich stimme dir zu = sana katılıyorum.' },
  { zeit: '2026-10-04', id: 'v626:frm', antwort: 'du vorschlägst', richtig: 'du schlägst vor', urteil: 'fast', text: 'Ayrılabilen ön ek Präsens\'te sona gider: du schlägst … vor.' },
  { zeit: '2026-10-04', id: 'v590:satz', antwort: 'verzihctet / verlauft', richtig: 'verlaufen', urteil: 'falsch', text: 'Partizip: verlaufen (ver- ile ge- yok, laufen güçlü → -en). Wir haben uns verlaufen.' },
  { zeit: '2026-10-04', id: 'n1286:wort', antwort: 'die Unterscrift', richtig: 'die Unterschrift', urteil: 'fast', text: 'Yazım: Unter-schrift (sch).' },
  { zeit: '2026-10-04', id: 'v243:stamm', antwort: 'fahrt, fuhr, gefahren', richtig: 'fährt, fuhr, ist gefahren', urteil: 'fast', text: 'er fährt (umlaut); hareket → ist gefahren.' },
  { zeit: '2026-10-04', id: 'v527:stamm', antwort: 'trefft, trof, hat getroffen', richtig: 'trifft, traf, hat getroffen', urteil: 'falsch', text: 'e → i: er trifft; Präteritum traf.' },
  { zeit: '2026-10-04', id: 'v346:stamm', antwort: 'kommt, kam, hat gekommen', richtig: 'kommt, kam, ist gekommen', urteil: 'fast', text: 'Hareket → sein: ist gekommen.' },
  { zeit: '2026-10-04', id: 'v347:stamm', antwort: 'kann, könnte', richtig: 'kann, konnte', urteil: 'falsch', text: 'konnte = -ebildi (Präteritum). könnte = -ebilirdi (Konjunktiv II). Modalda Perfekt sorulmuyor.' },
  { zeit: '2026-10-04', id: 'n0025:wort', antwort: 'der Amt', richtig: 'das Amt', urteil: 'fast', text: 'das Amt (çoğul die Ämter).' },
  { zeit: '2026-10-06', id: 'v592:satz', antwort: 'verletezt', richtig: 'verletzt', urteil: 'fast', text: 'Yazım: verletzt.' },
  { zeit: '2026-10-06', id: 'v423:satz', antwort: '—', richtig: 'Ich reagiere auf die E-Mail.', urteil: 'falsch', text: 'reagieren auf + Akk. (Bu soru parça parça biçimdeydi; artık hep düz Türkçe cümle geliyor.)' },
  { zeit: '2026-10-06', id: 'v425:satz', antwort: 'rechnet / rechnen', richtig: 'gerechnet', urteil: 'falsch', text: 'hatten … gerechnet: Plusquamperfekt, Partizip gerechnet.' },
  { zeit: '2026-10-06', id: 'n0432:nsatz', antwort: 'Gedahct / Gedacht', richtig: 'Gedicht', urteil: 'falsch', text: 'das Gedicht = şiir; gedacht = denken\'in Partizip\'i (düşündü). Karıştırma.' },
  { zeit: '2026-10-06', id: 'n0682:nsatz', antwort: 'Kritike', richtig: 'Kritiken', urteil: 'fast', text: 'Çoğul: die Kritiken.' },
  { zeit: '2026-10-06', id: 'v590:satz', antwort: 'verlauft', richtig: 'verlaufen', urteil: 'fast', text: 'Partizip verlaufen (-en).' },
  { zeit: '2026-10-06', id: 'n0025:wort', antwort: 'der Amt', richtig: 'das Amt', urteil: 'fast', text: 'İkinci kez der: das Amt.' },
  { zeit: '2026-10-06', id: 'v125:satz', antwort: '—', richtig: 'Will er sich beim Chef beschweren?', urteil: 'falsch', text: 'wollen başa, sich ve beim Chef ortada, beschweren sona.' },
  { zeit: '2026-10-06', id: 'v125:satz', antwort: '—', richtig: 'Ihr habt euch nicht bei eurem Vermieter beschwert.', urteil: 'falsch', text: 'ihr → euch, euer Vermieter → bei eurem Vermieter (Dat), Partizip beschwert.' },
  { zeit: '2026-10-06', id: 'v626:satz', antwort: 'Ich schläge vor', richtig: 'Ich schlage vor', urteil: 'fast', text: 'Umlaut yalnız du/er: du schlägst, er schlägt; ich schlage.' },
  { zeit: '2026-10-06', id: 'v673:satz', antwort: 'zweifelt', richtig: 'zweifeln', urteil: 'fast', text: 'Viele Leute = çoğul → zweifeln.' },
  { zeit: '2026-10-06', id: 'w0171:nsatz', antwort: 'folgend', richtig: 'folgenden', urteil: 'fast', text: 'auf den folgenden Seiten: çoğul Dativ, sıfat -en alır.' },
  { zeit: '2026-10-06', id: 'n1286:wort', antwort: 'der Unterschrift', richtig: 'die Unterschrift', urteil: 'fast', text: 'die Unterschrift (-schrift → die: die Schrift).' },
  { zeit: '2026-10-06', id: 'v149:satz', antwort: 'blitzt', richtig: 'geblitzt', urteil: 'falsch', text: 'Es hat … geblitzt: Perfekt, Partizip ge-…-t.' },
  { zeit: '2026-10-06', id: 'v148:stamm', antwort: 'bliebt, blieb, ist gelblieben', richtig: 'bleibt, blieb, ist geblieben', urteil: 'fast', text: 'Präsens bleibt (ei), Partizip geblieben.' },
  { zeit: '2026-10-06', id: 'v119:satz', antwort: 'Ruhigen', richtig: 'Beruhigen', urteil: 'fast', text: 'sich beruhigen: be- ön eki düşmez. Beruhigen Sie sich!' },
  { zeit: '2026-10-06', id: 'v672:satz', antwort: 'zusitmmen', richtig: 'stimme zu', urteil: 'falsch', text: 'Yazım + ayrılan ön ek: Ich stimme dir zu (zustimmen + Dat).' },
  { zeit: '2026-10-06', id: 'n0025:nsatz', antwort: 'Mann befindet sich das Arbeitsamt', richtig: 'Das Arbeitsamt befindet sich neben dem Busbahnhof.', urteil: 'falsch', text: "Cümle 'Das Arbeitsamt' ile başlar; 'Mann' fazlalık. neben + Dat: neben dem Busbahnhof." },
  { zeit: '2026-10-06', id: 'v425:satz', antwort: 'rechnen', richtig: 'gerechnet', urteil: 'falsch', text: 'habe … nicht gerechnet: Perfekt → Partizip ge-rechn-et.' },
  { zeit: '2026-10-06', id: 'v620:frm', antwort: 'hat verzicht', richtig: 'hat verzichtet', urteil: 'falsch', text: 'Partizip: verzichtet (ver- ile ge- yok, zayıf fiil → -et; ch+t okunması için e).' },
  { zeit: '2026-10-06', id: 'v429:satz', antwort: 'regnet', richtig: 'geregnet', urteil: 'falsch', text: 'Es hat geregnet: Perfekt → ge-regn-et.' },
  { zeit: '2026-10-06', id: 'v629:satz', antwort: 'Stellst du dich vor, dass ich die Prüfung besteht.', richtig: 'Stell dir vor, ich habe die Prüfung bestanden!', urteil: 'fast', text: 'sich(D) vorstellen → dir (Dativ), emir: Stell dir vor. Dass yerine düz cümle; Perfekt: habe … bestanden.' },
  { zeit: '2026-10-06', id: 'v646:frm', antwort: 'hat widerspricht', richtig: 'hat widersprochen', urteil: 'falsch', text: 'widersprechen güçlü fiil: widersprochen (sprechen → gesprochen), ge- yok.' },
  { zeit: '2026-10-06', id: 'v423:satz', antwort: 'reagieren', richtig: 'reagiert', urteil: 'falsch', text: 'Perfekt: hat … reagiert (-ieren fiillerinde ge- yok).' },
  { zeit: '2026-10-06', id: 'v149:satz', antwort: 'blitzt', richtig: 'geblitzt', urteil: 'falsch', text: 'Es hat geblitzt: Perfekt.' },
  { zeit: '2026-10-06', id: 'n0432:nsatz', antwort: 'Geduld', richtig: 'Gedicht', urteil: 'falsch', text: 'das Gedicht = şiir; die Geduld = sabır. Karıştırma.' },
  { zeit: '2026-10-06', id: 'n0179:wort', antwort: 'der Donnern', richtig: 'der Blitz', urteil: 'falsch', text: 'der Blitz = şimşek, der Donner = gök gürültüsü.' },
  { zeit: '2026-10-06', id: 'n1376:wort', antwort: 'die Wetterskad', richtig: 'die Wettervorhersage', urteil: 'falsch', text: 'Wetter + Vorhersage (vorhersagen = önceden söylemek).' },
  { zeit: '2026-10-06', id: 'n0587:wort', antwort: 'kühl', richtig: 'die Kälte', urteil: 'falsch', text: 'kühl sıfat (serin); die Kälte = soğuk (isim).' },
  { zeit: '2026-10-06', id: 'n0587:wort', antwort: 'die Kält', richtig: 'die Kälte', urteil: 'fast', text: 'Sonda -e: die Kälte.' },
  { zeit: '2026-10-06', id: 'n0691:wort', antwort: 'der Kunst', richtig: 'die Kunst', urteil: 'fast', text: 'die Kunst (çoğul die Künste).' },
  { zeit: '2026-10-06', id: 'n0207:wort', antwort: 'der Kust', richtig: 'die Burg', urteil: 'falsch', text: 'die Burg = kale; Kunst (sanat) ile karıştı.' },
  { zeit: '2026-10-06', id: 'v590:abr', antwort: 'sich verlieren', richtig: 'sich verlaufen', urteil: 'falsch', text: 'sich verlaufen = yürürken yolunu kaybetmek; sich verlieren başka (kaybolmak, dalıp gitmek).' },
  { zeit: '2026-10-06', id: 'p04:1', antwort: 'Üniverstät', richtig: 'Universität', urteil: 'falsch', text: 'Yazım: Uni-ver-si-tät, artikel die.' },
  { zeit: '2026-10-06', id: 'p04:5', antwort: 'Präsendation', richtig: 'Referat', urteil: 'falsch', text: 'das Referat = sunum/ödev; Präsentation farklı kelime, boşluğa Referat uyar.' },
  { zeit: '2026-10-06', id: 'p04:7', antwort: 'da', richtig: 'Kommilitonen', urteil: 'falsch', text: 'der Kommilitone n-Deklination: den Kommilitonen (Akk. / Dat. / çoğul).' },
  { zeit: '2026-10-06', id: 'p04:8', antwort: 'Melsa', richtig: 'Mensa', urteil: 'fast', text: 'Yazım: Mensa (n).' },
  { zeit: '2026-10-07', id: 'n0433:nsatz', antwort: 'Bitte seinen Sie ein bisschen', richtig: 'Bitte haben Sie etwas Geduld.', urteil: 'falsch', text: 'Geduld haben (sein değil). Sie-Emir: haben Sie.' },
  { zeit: '2026-10-07', id: 'v592:satz', antwort: 'verzichst', richtig: 'verletzt', urteil: 'falsch', text: 'Pass auf, dass du dich nicht verletzt: sich verletzen (verzichten ile karıştı).' },
  { zeit: '2026-10-07', id: 'v125:abr', antwort: 'beschweren bei d', richtig: 'sich beschweren bei (bei + Dat)', urteil: 'fast', text: 'Dönüşlü zamir sich unutma: sich beschweren bei.' },
  { zeit: '2026-10-07', id: 'v673:frm', antwort: 'zweifelt', richtig: 'hat gezweifelt', urteil: 'falsch', text: 'Perfekt = yardımcı + Partizip: er hat gezweifelt.' },
  { zeit: '2026-10-07', id: 'v425:luecke', antwort: 'rechnen', richtig: 'gerechnet', urteil: 'falsch', text: 'hatten … gerechnet: Plusquamperfekt.' },
  { zeit: '2026-10-07', id: 'n1286:wort', antwort: 'der Unterschrift', richtig: 'die Unterschrift', urteil: 'fast', text: 'die Unterschrift (-schrift → die).' },
  { zeit: '2026-10-07', id: 'v149:satz', antwort: 'blitzt', richtig: 'geblitzt', urteil: 'falsch', text: 'Perfekt: hat geblitzt (ikinci kez).' },
  { zeit: '2026-10-07', id: 'v590:abr', antwort: 'sich verandern', richtig: 'sich verlaufen', urteil: 'falsch', text: 'sich verändern = değişmek; sich verlaufen = yolunu kaybetmek.' },
  { zeit: '2026-10-08', id: 'v278:satz', antwort: 'fürchte', richtig: 'fürchtet', urteil: 'falsch', text: 'Özne Sie (o): sie fürchtet sich; ich fürchte mich.' },
  { zeit: '2026-10-08', id: 'v629:refl', antwort: 'stelle vor', richtig: 'stellt vor', urteil: 'falsch', text: 'Özne Er: stellt sich ... vor. Ayrılan ön ek sona.' },
  { zeit: '2026-10-08', id: 'p01:4', antwort: 'Sichertenkarte', richtig: 'Versichertenkarte', urteil: 'falsch', text: 'die Versichertenkarte = sigorta kartı (Ver-sicher-ten-karte).' },
  { zeit: '2026-10-08', id: 'p01:6', antwort: 'verschriebt', richtig: 'verschreibt', urteil: 'fast', text: 'Güçlü fiil: er verschreibt (Präsens -t), Präteritum verschrieb.' },
  { zeit: '2026-10-08', id: 'p01:9', antwort: 'die Tablette', richtig: 'Tablette', urteil: 'falsch', text: 'Boşlukta artikel yoktu: die zaten metinde vardı.' },
  { zeit: '2026-10-08', id: 'w0599:prod', antwort: 'entspanned sein', richtig: 'eingespannt sein', urteil: 'falsch', text: 'eingespannt sein = çok meşgul; entspannt = rahat (zıt anlam!).' },
  { zeit: '2026-10-08', id: 'v111:refl', antwort: 'bemühen', richtig: 'bemüht', urteil: 'falsch', text: 'Perfekt: hat sich bemüht (be- ile ge- yok).' },
  { zeit: '2026-10-08', id: 'v142:abr', antwort: 'beschwerten', richtig: 'beweisen (Akk)', urteil: 'falsch', text: 'beweisen = kanıtlamak (beschweren değil).' },
  { zeit: '2026-10-08', id: 'v509:satz', antwort: 'streitet', richtig: 'gestritten', urteil: 'falsch', text: 'habt euch gestritten: Perfekt, güçlü fiil streiten – stritt – gestritten.' },
  { zeit: '2026-10-08', id: 'v063:abr', antwort: '—', richtig: 'sich aufregen über (über + Akk)', urteil: 'falsch', text: 'Ich rege mich über den Lärm auf.' },
  { zeit: '2026-10-08', id: 'v545:abr', antwort: 'übertragen?', richtig: 'übertreiben (Akk)', urteil: 'falsch', text: 'übertreiben = abartmak; übertragen = aktarmak/yayınlamak.' },
  { zeit: '2026-10-08', id: 'v063:abr', antwort: 'sich anstrenget über', richtig: 'sich aufregen über', urteil: 'falsch', text: 'sich anstrengen = çabalamak; sich aufregen = sinirlenmek.' },
  { zeit: '2026-10-08', id: 'v466:abr', antwort: '—', richtig: 'schweigen', urteil: 'falsch', text: 'schweigen = susmak (schweigen – schwieg – geschwiegen).' },
  { zeit: '2026-10-08', id: 'v119:satz', antwort: 'beruigt', richtig: 'beruhigt', urteil: 'fast', text: 'Yazım: beruhigt (h).' },
];
